# Variables
[env]
FUZZER_NAME = 'fuzzer_libstr'
CARGO_TARGET_DIR = { value = "${PROJECT_DIR}/target", condition = { env_not_set = [
  "CARGO_TARGET_DIR",
] } }
PROFILE = { value = "release", condition = { env_not_set = ["PROFILE"] } }
PROFILE_DIR = { source = "${PROFILE}", default_value = "release", mapping = { "release" = "release", "dev" = "debug" }, condition = { env_not_set = [
  "PROFILE_DIR",
] } }
LIBAFL_CC = '${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_cc'
LIBAFL_CXX = '${CARGO_TARGET_DIR}/${PROFILE}/libafl_cxx'
LIBAFL_LIBTOOL = '${CARGO_TARGET_DIR}/${PROFILE}/libafl_libtool'
FUZZER = '${CARGO_TARGET_DIR}/${PROFILE_DIR}/${FUZZER_NAME}'
PROJECT_DIR = { script = ["pwd"] }
JSON_PATH = { script = ["${PROJECT_DIR}/smart_pwd ${PROJECT_DIR}/../../../json/"], condition = { env_not_set = ["JSON_PATH"] } }
CFG_LD = { value = "" }
PROJECT_ROOT_DIR = { script = ["${PROJECT_DIR}/smart_pwd ${PROJECT_DIR}/../../.."] }
CFG_GEN_PASS = { value = "${PROJECT_ROOT_DIR}/SeedScheduling/SanitizerCoveragePCGUARD.so", condition = { env_not_set = ["CFG_GEN_PASS"] } }

[tasks.instrumentation]
condition = { files_not_exist = ["${CFG_GEN_PASS}"]}
script_runner = "@shell"
script = '''
cd ${PROJECT_ROOT_DIR}/SeedScheduling
make
ls ${CFG_GEN_PASS}
'''

# should be set in the environment if libafl_cc
# is built with the `cfg-ld` feature enabled

# CFG_LD = { value = "/home/anonymous/LibAFL/libafl_cc/src/cfg-ld.py", condition = { env_not_set = ["CFG_LD"] } }

# This project does not have to obtain source code from the internet.

[tasks.cc]
condition = { files_not_exist = ["${LIBAFL_CC}"] }
script_runner = "@shell"
script = '''
JSON_PATH=${JSON_PATH} cargo build --profile ${PROFILE}
'''
dependencies = ["instrumentation"]

[tasks.cxx]
dependencies = ["cc"]

[tasks.ar]
dependencies = ["cc"]

[tasks.lib]
condition = { files_not_exist = ["${PROJECT_DIR}/libstr/libstr.a"] }
script_runner = "@shell"
script = '''
cd "${PROJECT_DIR}"
make -C libstr CC="${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_cc" CXX="${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_cxx" AR="${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_ar"
'''
dependencies = ["cc", "cxx", "ar"]

[tasks.harness_obj]
condition = { files_not_exist = ["${PROJECT_DIR}/harness.o"]}
command = "${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_cxx"
args = [
  "-c",
  "${PROJECT_DIR}/harness.cc",
  "-I${PROJECT_DIR}/",
  "-o",
  "${PROJECT_DIR}/harness.o"
]
dependencies = ["cxx", "cc"]

[tasks.fuzzer]
command = "${CARGO_TARGET_DIR}/${PROFILE_DIR}/libafl_cxx"
args = [
  "${PROJECT_DIR}/harness.o",
  "${PROJECT_DIR}/libstr/libstr.a",
  "-o",
  "${FUZZER_NAME}",
]
dependencies = ["lib", "cxx", "cc", "harness_obj"]

[tasks.cfg]
script_runner = "@shell"
script = '''
  cd ${PROJECT_DIR} && ./build_cfg.sh ${FUZZER_NAME}.coverage
'''
dependencies = ["fuzzer"]

[tasks.run]
description = "Runs the fuzzer."
script_runner = '@shell'
script = '''
AFL_CFG_PATH=${PROJECT_DIR}/${PROJECT_DIR}_sancov_cfg ./fuzzer_libstr.asan --input ${PROJECT_DIR}/input --cores 0
'''
dependencies = ["fuzzer", "cfg"]

[tasks.clean_cargo]
description = "Runs the cargo clean command."
category = "Cleanup"
command = "cargo"
args = ["clean"]

[tasks.clean_libstr]
description = "Runs the make clean command in the libstr directory."
category = "Cleanup"
command = "make"
args = ["-C", "libstr", "clean"]

[tasks.clean_miscellaneous]
category = "Cleanup"
script_runner = "@shell"
script = '''
rm -f ${PROJECT_DIR}/*.o ${PROJECT_DIR}/*.cfg ${PROJECT_DIR}/*.csv ${PROJECT_DIR}/fuzzer_libstr* ${PROJECT_DIR}/.*.bc ${PROJECT_DIR}/.*.dot
'''

[tasks.full_clean]
description = "Runs both clean tasks."
category = "Cleanup"
dependencies = ["clean_cargo", "clean_libstr", "clean_miscellaneous"]

[tasks.clean]
dependencies = ["full_clean"]
